import 'dart:async';
import 'dart:io';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'secrets.dart';

/// The game sounds (generated by tool/make_sounds.py).
enum Sfx { clack, pocket, place, click, card, dice, thud, eat, fall, win, lose }

/// Plays short sound effects. Can be switched off in the settings; follows
/// the silent switch on iOS and mixes with music that is playing.
class Sound {
  Sound._();

  static final ValueNotifier<bool> enabled = ValueNotifier(true);
  static const _key = 'sound.enabled';

  static final Map<String, Future<AudioPool?>> _pools = {};
  static final Map<Sfx, DateTime> _lastPlayed = {};

  /// No sound in widget tests (there is no audio plugin).
  static final bool _testing =
      !kIsWeb && Platform.environment.containsKey('FLUTTER_TEST');

  static Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    enabled.value = prefs.getBool(_key) ?? true;
  }

  static Future<void> setEnabled(bool on) async {
    enabled.value = on;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_key, on);
    if (on) play(Sfx.click);
  }

  /// Plays [sfx]. The same sound is not repeated faster than [minGap]
  /// (e.g. many billiard balls touching at once).
  static void play(
    Sfx sfx, {
    double volume = 1,
    Duration minGap = const Duration(milliseconds: 40),
  }) {
    if (!enabled.value || _testing || volume <= 0.01) return;
    final now = DateTime.now();
    final last = _lastPlayed[sfx];
    if (last != null && now.difference(last) < minGap) return;
    _lastPlayed[sfx] = now;
    unawaited(_start(sfx, volume.clamp(0.0, 1.0)));
  }

  static Future<void> _start(Sfx sfx, double volume) async {
    try {
      // The secret retro mode swaps in 8-bit versions.
      final path = Secrets.on(Secret.retro)
          ? 'sounds/retro/${sfx.name}.wav'
          : 'sounds/${sfx.name}.wav';
      final pool = await _pools.putIfAbsent(path, () => _createPool(path));
      await pool?.start(volume: volume);
    } catch (_) {
      // Sound is a nice extra; never let it break a game.
    }
  }

  static Future<AudioPool?> _createPool(String path) async {
    try {
      return await AudioPool.create(
        source: AssetSource(path),
        maxPlayers: 4,
        audioContext: AudioContextConfig(
          focus: AudioContextConfigFocus.mixWithOthers,
          respectSilence: true,
        ).build(),
      );
    } catch (_) {
      return null;
    }
  }
}
